export const metadata = {
  title: "About Us",
  description: "Generated by Next.js",
};

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section>{children}</section>;
}
