import "./global.scss";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Container from "@/components/Container/Container";

export const metadata = {
  title: "Future Evic Project",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Container>
          <Header></Header>
          {children}
          <Footer></Footer>
        </Container>
      </body>
    </html>
  );
}
